"use client";
import { useEffect, useState, useCallback } from "react";
import { getFirebaseAuth, onAuthChanged, signInWithDiscordCustomToken, getIdToken, signOutFirebase } from "@/lib/firebase-client";
import { deriveKeyFromPin, exportKeyToBase64, importKeyFromBase64, STORAGE_BACKUP_KEY } from "@/lib/backup-crypto";
import { isAllowedOrigin, STORAGE_BACKUP_ENABLED, STORAGE_LAST_BACKUP, STORAGE_LAST_BACKUP_SIZE, formatBytes, formatLocalTimestamp, backupToCloud, restoreFromCloud, deleteCloudBackup, disableBackupsLocal } from "@/lib/backup";

type DiscordUser = { id: string; username: string; avatar?: string|null }|null;
const STORAGE_DISCORD_USER = "dnd-chant-discord-user-v1";

export function useBackup(opts: { characters:any[]; schoolLangsPerChar:Record<string,any>; extrasPerChar:Record<string,any>; activeId:string; helpTemplate:string }) {
  const [user,setUser]=useState<{firebase:any;discord:DiscordUser}>({firebase:null,discord:null});
  const [status,setStatus]=useState(""); const [isBusy,setIsBusy]=useState(false);
  const [ui,setUi]=useState<{showEnableBackups:boolean;lastBackupISO:string|null;lastBackupSize:number|null;backupEnabled:boolean}>({showEnableBackups:false,lastBackupISO:null,lastBackupSize:null,backupEnabled:false});
  const [pinDialog,setPinDialog]=useState<{open:boolean;mode:"backup"|"restore";resolve?:(pin:string|null)=>void}>({open:false,mode:"backup"});

  useEffect(()=>{ let unsub:(()=>void)|null=null; try{ unsub=onAuthChanged(async fb=>{ if(fb){ 
    let restored: DiscordUser=null; try{ const raw=localStorage.getItem(STORAGE_DISCORD_USER); if(raw){ const j=JSON.parse(raw); if(j?.id) restored={id:String(j.id),username:String(j.username||""),avatar:j.avatar||null}; } }catch{}
    if(!restored){ try{ const tr:any = await (fb as any).getIdTokenResult?.(); const c=tr?.claims; if(c?.discordId) restored={id:String(c.discordId),username:String(c.discordUsername||""),avatar:c.discordAvatar||null}; }catch{} }
    setUser(p=>({firebase:fb,discord:p.discord||restored|| (fb as any).uid?.startsWith("discord:")?{id:(fb as any).uid.slice(8),username:restored?.username||"" ,avatar:restored?.avatar||null}:null })); if(restored){ try{localStorage.setItem(STORAGE_DISCORD_USER,JSON.stringify(restored));}catch{} } setUi(p=>({...p,backupEnabled:true})); try{localStorage.setItem(STORAGE_BACKUP_ENABLED,"1");}catch{} } else setUser(p=>({firebase:null,discord:p.discord})); }); }catch{} return()=>{ if(unsub) unsub(); }; },[]);

  useEffect(()=>{
    try{ if(localStorage.getItem(STORAGE_BACKUP_ENABLED)==="1") setUi(p=>({...p,backupEnabled:true})); const lb=localStorage.getItem(STORAGE_LAST_BACKUP); if(lb) setUi(p=>({...p,lastBackupISO:lb})); const sz=localStorage.getItem(STORAGE_LAST_BACKUP_SIZE); if(sz){ const n=parseInt(sz,10); if(!isNaN(n)) setUi(p=>({...p,lastBackupSize:n})); } const du=localStorage.getItem(STORAGE_DISCORD_USER); if(du){ const j=JSON.parse(du); if(j?.id) setUser(p=>({firebase:p.firebase,discord:{id:String(j.id),username:String(j.username||""),avatar:j.avatar||null}})); } }catch{}
    const onMessage=async(e:MessageEvent)=>{ if(!isAllowedOrigin(e.origin)) return; const d:any=e.data; if(!d||typeof d!=="object") return;
      if(d.type==="discord-auth-success"&&d.customToken){
        const exp=sessionStorage.getItem("dnd-chant-discord-state"); if(!exp||!d.state||d.state!==exp){ setStatus("Discord state mismatch – try again"); return; }
        try{ setIsBusy(true); setStatus("Signing in with Discord…"); const fb=await signInWithDiscordCustomToken(d.customToken); const du=d.discordUser?{id:d.discordUser.id,username:d.discordUser.username,avatar:d.discordUser.avatar}:null; setUser({firebase:fb,discord:du}); if(du){ try{localStorage.setItem(STORAGE_DISCORD_USER,JSON.stringify(du));}catch{} } setUi(p=>({...p,backupEnabled:true})); try{localStorage.setItem(STORAGE_BACKUP_ENABLED,"1");}catch{}
          const pending=sessionStorage.getItem("dnd-chant-pending-pin"); if(pending&&/^\d{6}$/.test(pending)){ const uid=(fb as any)?.uid||`discord:${d.discordUser?.id||""}`; const key=await deriveKeyFromPin(pending,uid); localStorage.setItem(STORAGE_BACKUP_KEY,await exportKeyToBase64(key)); setStatus("Backing up…"); try{ const res=await backupToCloud({characters:opts.characters,schoolLangsPerChar:opts.schoolLangsPerChar,extrasPerChar:opts.extrasPerChar,activeId:opts.activeId,helpTemplate:opts.helpTemplate,ddbLink:(()=>{try{return localStorage.getItem("dnd-chant-ddb-link-v1");}catch{return null;}})()},uid,pending); const now=new Date(res.at || new Date().toISOString()); setUi(p=>({...p,lastBackupISO:now.toISOString(),lastBackupSize:res.size||null,showEnableBackups:false})); try{localStorage.setItem(STORAGE_LAST_BACKUP,now.toISOString()); if(res.size) localStorage.setItem(STORAGE_LAST_BACKUP_SIZE,String(res.size));}catch{} setStatus(""); sessionStorage.removeItem("dnd-chant-pending-pin"); sessionStorage.removeItem("dnd-chant-discord-state"); }catch(err:any){ setStatus(`Backup failed: ${String(err?.message||err).slice(0,200)}`);} } else { setStatus("Discord login complete – set PIN to backup"); setUi(p=>({...p,showEnableBackups:true})); } }catch(err:any){ setStatus(`Discord sign-in failed: ${String(err?.message||err).slice(0,200)}`);} finally{ setIsBusy(false);} } else if(d.type==="discord-auth-error"){ setStatus(`Discord auth failed: ${d.error||"unknown"}`); setIsBusy(false); }
    };
    window.addEventListener("message",onMessage); return()=>window.removeEventListener("message",onMessage);
  },[opts.characters,opts.schoolLangsPerChar,opts.extrasPerChar,opts.activeId,opts.helpTemplate]);

  const onEnableBackups=useCallback((pin:string)=>{ if(!/^\d{6}$/.test(pin)){ setStatus("PIN must be 6 digits"); return; } const clientId=process.env.NEXT_PUBLIC_DISCORD_CLIENT_ID||""; if(!clientId){ setStatus("Discord client ID not configured"); return; } try{ sessionStorage.setItem("dnd-chant-pending-pin",pin); const state=crypto.randomUUID(); sessionStorage.setItem("dnd-chant-discord-state",state); const origin=typeof window!=="undefined"?window.location.origin:"https://chants-506202.web.app"; const redirect=origin.includes("localhost")?`${origin}/api/discord-auth/callback`:"https://chants-506202.web.app/api/discord-auth/callback"; const authUrl=`https://discord.com/oauth2/authorize?client_id=${encodeURIComponent(clientId)}&response_type=code&scope=identify&redirect_uri=${encodeURIComponent(redirect)}&state=${encodeURIComponent(state)}&prompt=consent`; setIsBusy(true); setStatus("Opening Discord login…"); const w=window.open(authUrl,"discord-auth","width=480,height=720"); if(!w) window.location.href=authUrl; }catch(e:any){ setStatus(`Enable failed: ${String(e?.message||e).slice(0,200)}`); setIsBusy(false);} },[]);

  const onBackupAction=useCallback(async(action:"backup"|"restore")=>{
    if(action==="backup"){
      try{ const idTok=await getIdToken(); if(!idTok){ setStatus("Not signed in – enable backups first"); return; } const uid=(user.firebase as any)?.uid||""; let key:CryptoKey|null=null; try{ const b64=localStorage.getItem(STORAGE_BACKUP_KEY); if(b64) key=await importKeyFromBase64(b64);}catch{} if(!key){ const pin=await new Promise<string|null>(res=>setPinDialog({open:true,mode:"backup",resolve:res})); if(!pin||!/^\d{6}$/.test(pin)){ setStatus("Backup cancelled – invalid PIN"); setPinDialog({open:false,mode:"backup"}); return; } key=await deriveKeyFromPin(pin,uid); localStorage.setItem(STORAGE_BACKUP_KEY,await exportKeyToBase64(key)); setPinDialog({open:false,mode:"backup"}); } setStatus("Backing up…"); const payload={characters:opts.characters,schoolLangsPerChar:opts.schoolLangsPerChar,extrasPerChar:opts.extrasPerChar,activeId:opts.activeId,helpTemplate:opts.helpTemplate,ddbLink:(()=>{try{return localStorage.getItem("dnd-chant-ddb-link-v1");}catch{return null;}})()}; const res=await backupToCloud(payload,uid); const now=new Date(res.at || new Date().toISOString()); setUi(p=>({...p,lastBackupISO:now.toISOString(),lastBackupSize:res.size||null})); try{localStorage.setItem(STORAGE_LAST_BACKUP,now.toISOString()); if(res.size) localStorage.setItem(STORAGE_LAST_BACKUP_SIZE,String(res.size));}catch{} setStatus("");}catch(e:any){ setStatus(`Backup failed: ${String(e?.message||e).slice(0,200)}`);} 
    } else {
      try{ const idTok=await getIdToken(); if(!idTok){ setStatus("Not signed in – enable backups first"); return; } setStatus("Fetching backup…"); const uid=(user.firebase as any)?.uid||""; let key:CryptoKey|null=null; try{ const b64=localStorage.getItem(STORAGE_BACKUP_KEY); if(b64) key=await importKeyFromBase64(b64);}catch{} if(!key){ const pin=await new Promise<string|null>(res=>setPinDialog({open:true,mode:"restore",resolve:res})); if(!pin||!/^\d{6}$/.test(pin)){ setStatus("Restore cancelled – invalid PIN"); setPinDialog({open:false,mode:"restore"}); return; } key=await deriveKeyFromPin(pin,uid); localStorage.setItem(STORAGE_BACKUP_KEY,await exportKeyToBase64(key)); setPinDialog({open:false,mode:"restore"}); } const data=await restoreFromCloud(uid); if(Array.isArray(data.characters)) localStorage.setItem("dnd-chant-characters-v1",JSON.stringify(data.characters)); if(data.schoolLangsPerChar) localStorage.setItem("dnd-chant-school-langs-v1",JSON.stringify(data.schoolLangsPerChar)); if(data.extrasPerChar) localStorage.setItem("dnd-chant-extras-v1",JSON.stringify(data.extrasPerChar)); if(typeof data.activeId==="string") localStorage.setItem("dnd-chant-active-character-v1",data.activeId); if(typeof data.helpTemplate==="string") localStorage.setItem("dnd-chant-help-template-v1",data.helpTemplate); if(data.ddbLink) try{localStorage.setItem("dnd-chant-ddb-link-v1",data.ddbLink);}catch{} setStatus("Restore complete – reloading"); setTimeout(()=>window.location.reload(),500);}catch(e:any){ const m=String(e?.message||e); if(m.includes("Wrong PIN")) setStatus(m); else setStatus(`Restore failed: ${m.slice(0,200)}`);} 
    }
  },[user.firebase,opts.characters,opts.schoolLangsPerChar,opts.extrasPerChar,opts.activeId,opts.helpTemplate]);

  const onDisable=useCallback(async(mode:"disable"|"delete"="disable")=>{
    if(mode==="delete"){ if(!window.confirm("Delete cloud backup? This cannot be undone.")) return; try{ await deleteCloudBackup(); setStatus("Cloud backup deleted"); setUi(p=>({...p,lastBackupISO:null,lastBackupSize:null})); }catch(e:any){ setStatus(`Delete failed: ${String(e?.message||e).slice(0,200)}`);} return; }
    if(!window.confirm("Disable backups on this device? You will need PIN and Discord login to restore again.")) return; try{ await signOutFirebase(); }catch{} setUser({firebase:null,discord:null}); setUi({showEnableBackups:false,lastBackupISO:null,lastBackupSize:null,backupEnabled:false}); disableBackupsLocal(); try{localStorage.removeItem(STORAGE_DISCORD_USER);}catch{} setStatus("Backups disabled on this device");
  },[]);

  return { user, status, isBusy, ui, setUi, onEnableBackups, onBackupAction, onDisable, setStatus, pinDialog, setPinDialog };
}
